"""
Integration Tests (End-to-End).
"""

import importlib.util
import shutil
import unittest
from pathlib import Path

from normadocs.formatters import get_formatter
from normadocs.pandoc_client import PandocRunner
from normadocs.pdf_generator import PDFGenerator
from normadocs.preprocessor import MarkdownPreprocessor

# Integration tests usually require real tools installed (Pandoc)
# We skip if pandoc is not found to avoid failing in environments without it.
PANDOC_AVAILABLE = shutil.which("pandoc") is not None


@unittest.skipUnless(PANDOC_AVAILABLE, "Pandoc not found")
class TestIntegration(unittest.TestCase):
    def setUp(self):
        self.test_dir = Path("tests/temp_integration")
        self.test_dir.mkdir(exist_ok=True)
        self.md_file = self.test_dir / "integration_test.md"
        self.md_file.write_text(
            """
**My Title**

Author Name
2023-01-01

# Introduction
This is a test paragraph.

# Methods
We used integration testing.

| Col 1 | Col 2 |
|-------|-------|
| Val A | Val B |
| Val C | Val D |
""",
            encoding="utf-8",
        )

    def tearDown(self):
        if self.test_dir.exists():
            shutil.rmtree(self.test_dir)

    def test_full_pipeline_apa(self):
        """Test partial pipeline with APA formatter."""
        print("\n  [Integration] Starting APA pipeline test...")
        self._run_pipeline("apa")

    def test_full_pipeline_icontec(self):
        """Test partial pipeline with ICONTEC formatter."""
        print("\n  [Integration] Starting ICONTEC pipeline test...")
        self._run_pipeline("icontec")

    def _run_pipeline(self, style: str):
        # 1. Preprocess
        processor = MarkdownPreprocessor()
        clean_md, meta = processor.process(self.md_file.read_text())

        # 2. Pandoc
        output_docx = self.test_dir / f"output_{style}.docx"
        runner = PandocRunner()
        success = runner.run(clean_md, str(output_docx))
        self.assertTrue(success, "Pandoc conversion failed")

        # 3. Formatting
        try:
            formatter = get_formatter(style, str(output_docx))
            formatter.process(meta)
            formatter.save(str(output_docx))
            print(f"  [Integration] {style.upper()} Formatting applied successfully.")
        except Exception as e:
            self.fail(f"{style.upper()} Formatting crashed: {e}")

        # 4. PDF Generation (Optional, mimics CLI behavior)
        # We try strict fallback if LibreOffice isn't there, or just skip if neither work.
        # But for test purposes, we want to ensure code runs.
        # We can't guarantee LibreOffice or WeasyPrint are installed in CI/dev env.
        # So we assert that IF they are present, it works.
        output_pdf = self.test_dir / f"output_{style}.pdf"

        has_libreoffice = shutil.which("libreoffice") is not None
        has_weasyprint = importlib.util.find_spec("weasyprint") is not None

        if has_libreoffice:
            print("  [Integration] Testing LibreOffice PDF generation...")
            success_pdf = PDFGenerator.convert_with_libreoffice(
                str(output_docx), str(self.test_dir)
            )
            # LibreOffice might fail in headless CI if no display, so be lenient or check specific return
            # But if it returns True, file must exist
            if success_pdf:
                # The filename generated by libreoffice is based on input stem
                expected_pdf = self.test_dir / f"output_{style}.pdf"
                self.assertTrue(
                    expected_pdf.exists(), "PDF file should exist after LibreOffice success"
                )

        elif has_weasyprint:
            print("  [Integration] Testing WeasyPrint PDF generation...")
            success_pdf = PDFGenerator.convert_with_weasyprint(clean_md, str(output_pdf))
            if success_pdf:
                self.assertTrue(
                    output_pdf.exists(), "PDF file should exist after WeasyPrint success"
                )
        else:
            print("  [Integration] Skipping PDF test (No LibreOffice/WeasyPrint found)")


if __name__ == "__main__":
    unittest.main()
